name: Local Config
version: 1.0.0
schema: v1
models:
  - name: gemma4-e4b
    provider: openai
    model: google/gemma-4-e4b
    apiBase: http://localhost:11434/v1
    roles:
      - chat
      - edit
    contextLength: 8192
    completionOptions:
      maxTokens: 2048

  - name: gemma-4-e2b
    provider: openai
    model: gemma-4-e2b-it-uncensored
    roles:
      - autocomplete
    apiBase: http://localhost:11434/v1
    contextLength: 4096
